const SUPPORTED_LANGS = [
    { code: 'en', label: 'English', flag: '🇺🇸' },
    { code: 'zh-TW', label: '繁體中文', flag: '🇹🇼' },
    { code: 'zh-CN', label: '简体中文', flag: '🇨🇳' },
    { code: 'ja', label: '日本語', flag: '🇯🇵' },
    { code: 'ko', label: '한국어', flag: '🇰🇷' }
];

const LANG_DATA = {
    'zh-TW': {
        title: 'ContextCarry',
        status_ready: '準備就緒',
        status_scanning: '正在掃描...',
        label_prefix: '自訂前綴提示詞:',
        placeholder: '在此輸入要給 AI 的前導指令...',
        btn_scan: '重新掃描頁面',
        btn_scan_done: '已重新掃描',
        btn_select_all: '全選所有訊息',
        btn_unselect_all: '取消全選',
        btn_dl: '輸出籃子',
        btn_copy: '複製到剪貼簿',
        label_transfer: '轉移並開啟 (Cross-LLM):',
        msg_detected: '偵測到 {n} 則訊息',
        msg_selected: '已選取: {n} 則',
        alert_no_selection: '請先選取對話或加入採集籃！',
        alert_copy_done: '內容已複製！',
        alert_fail: '操作失敗，請檢查權限',
        btn_add_title: '加入此段落 (Shift 可連選)',
        toast_autofill: 'Context-Carry: 已自動填入內容.',
        default_prompt: `請針對以下內容進行總結，列出重點摘要與結論：`,
        label_basket: '🧺 跨視窗採集籃 (Basket):',
        btn_add_basket: '加入 (+)',
        btn_clear_basket: '清空',
        btn_paste_basket: '填入此視窗',
        basket_status: '目前有 {n} 筆資料 (點擊預覽 ▼)',
        basket_status_empty: '採集籃是空的',
        toast_basket_add: '已加入採集籃 🧺',
        toast_basket_clear: '採集籃已清空 🗑️',
        preview_del_tooltip: '刪除此筆資料',
        preview_drag_hint: '可拖曳排序 ⇅ (懸停可看詳情)',
        token_est: '📊 預估 Token:',
        token_warn_title: '⚠️ Token 數量警告',
        token_warn_msg: '預估內容 ({est}) 超過了 {platform} 的建議限制 ({limit})。\n\n強行轉移可能會導致記憶遺失。\n是否仍要繼續？',
        btn_paint: '🖌️ 圈選',
        paint_tooltip: '圈選畫面區域文字',
        toast_enter_paint: '進入圈選模式 (按 ESC 退出)',
        paint_no_text: '未選取到任何文字',
        preview_title: '📝 <b>確認擷取內容 (Preview)</b>',
        preview_words: '字數',
        preview_cancel: '取消',
        preview_confirm: '加入採集',
        source_area_select: ' (圈選)',
        alert_llm_only: '自動填入功能 (Auto-fill) 僅支援(ChatGPT, Claude, Gemini, Grok)',
        btn_summary: 'AI 總結',
        btn_new_doc: '建立筆記',
        enter_new_doc: '請輸入內容：',
        ai_settings_title: 'AI 設定',
        ai_settings_endpoint: 'API 網址 (Endpoint)',
        ai_settings_api_key: 'API 金鑰 (Key)',
        ai_settings_save: '儲存設定',
        ai_unconfigured: '尚未設定 AI，請先進行設定。',
        ai_response_title: 'AI 回應',
        ai_response_tab_response: '回應',
        ai_response_tab_context: '上下文',
        ai_summary_sending: 'AI 正在總結中...',
        ai_summary_error: 'AI 請求失敗',
        drawer_toggle: '進階選項 & 採集籃',
        ai_setting_tab: 'AI 設定',
        ai_response_tab: 'AI 回應',
        ai_config_title: 'AI 設定',
        ai_provider: '模型供應商 (Provider)',
        ai_api_key: 'API 金鑰 (Key)',
        ai_model: '模型名稱 (Model)',
        ai_endpoint_toggle: 'API 網址 (Endpoint)',
        ai_save: '儲存設定',
        ai_modal_title: 'AI 回應',
        ai_modal_processing: 'AI 思考中...',
        ai_modal_done: '✅ 完成',
        ai_tab_res: 'AI 回應',
        ai_tab_ctx: '發送內容 (編輯)',
        btn_resend: '🔄 更新內容並重試',
        btn_save_file: '⬇️ 存為檔案',
        btn_paste: '📋 填入目前視窗',
        btn_send_all: '🚀 貼到全部',
        btn_copy_res: '複製',
        btn_clear_res: '清空',
        btn_min_restore: '還原視窗',
        btn_lang_title: '切換語言',
        btn_theme_title: '切換深色模式',
        btn_close_title: '關閉面板',
        hint_shortcut_lang: ' (Alt+L)',
        hint_shortcut_paint: ' (Alt+C)',
        hint_shortcut_toggle: ' (Alt+M)',
        btn_switch_ui: '切換介面風格',
        hatch_expand: '▼ 展開貨艙',
        hatch_retract: '▲ 收起貨艙',
        btn_quick_settings: '⚙️ AI 設定',
        unlock_title: '🔒 啟用 AI 功能',
        unlock_warning: `⚠️ <b>重要：AI功能採用「自備金鑰-BYO Key」模式。</b>
<br/><br/>
<ul>
    <li><b>金鑰由您控制：</b>您提供的API 金鑰<b>僅儲存在您瀏覽器的本地儲存空間</b>中。</li><br/><br/>
    <li><b>數據保持本地：</b>所有內容<b>絕不會被傳輸到 Context-Carry 開發者的任何伺服器</b>。所有 AI 請求都是從您的瀏覽器直接發送到您選擇的第三方 LLM 供應商。</li><br/><br/>
    <li><b>費用由您承擔：</b>這些 LLM 服務<b>不是免費的</b>，將根據您的金鑰和使用量向您的帳戶收取費用。</li>
</ul>
<br/>
啟用此功能，即表示您<b>完全知情</b>並同意使用您自己的金鑰，並由您自行承擔所有第三方服務費用。`,
        unlock_cancel: '取消',
        unlock_confirm: '我了解，啟用 AI',
        unlock_enabling: '啟用中...',
        unlock_toast_success: 'AI 功能已啟用 🔓',
        ai_panel_active: '啟用面板 {n}',
        ai_panel_empty_title: '等待輸入',
        ai_panel_empty_msg: '<span id="goto-edit-{n}" style="color:#00d2ff; cursor:pointer; text-decoration:underline;">編輯</span> 加入內容',
        ai_panel_status_ready: '就緒。點擊 🚀 開始。',
        ai_panel_copy_tooltip: '複製回應',
        ai_panel_close_tooltip: '停用面板',
        ai_panel_not_activated: '面板 {n} 未啟用',
        ai_import_basket_tooltip: '匯入採集籃內容',
        ai_copy_ctx_tooltip: '複製此內容',
        ai_ctx_placeholder: '在此輸入上下文...',
        ai_save_indicator_saving: '儲存中...',
        ai_save_indicator_saved: '已儲存 ✓',
        label_load_profile: '讀取設定檔',
        label_config_name: '設定名稱 (Alias)',
        label_ai_provider: '模型供應商 (Provider)',
        label_api_key: 'API 金鑰 (Key)',
        label_target_model: '目標模型 (Model)',
        label_endpoint: 'API 網址 (Endpoint)',
        option_new_profile: '-- 建立新設定 --',
        option_loading: '載入中...',
        btn_align: '🔁 同步全部',
        btn_align_tooltip: '將面板 {n} 的內容複製到「所有」面板',
        msg_align_confirm: '確定要將面板 {n} 的內容複製覆蓋到其他所有面板嗎？',
        btn_apply_view: '套用並檢視 >>',
        btn_start_all: '⚡ 全部開始',
        btn_copy_all_res: '📋 複製全部',
        warn_resource_title: '⚠️ 資源消耗警告',
        warn_resource_msg1: '即將啟用多節點視窗 (Multi-Node View)。',
        warn_resource_msg2: '這將最多同時發送 3 個 AI 請求。',
        warn_resource_msg3: '請確認所有面板皆已設定 API Key，以免產生意外費用或錯誤。',
        btn_proceed: '繼續執行',
        btn_abort: '取消',
        msg_no_ready_panels: '沒有準備就緒的面板 (請檢查內容或設定)',
        msg_all_copied: '已複製所有回應！',
        msg_context_synced: '上下文已同步',
        msg_imported_basket: '已匯入 {n} 筆資料至面板 {i}',
        msg_basket_empty: '採集籃是空的！',
        ph_config_name: '例如: 工作用',
        ph_api_key: 'sk-...',
        ph_model: '例如: gpt-4o-mini',
        ai_panel_resend: '開始 / 重試',
        btn_layout_single: '單頁模式',
        btn_layout_quad: '多頁模式',
        mech_header: '// 神經網路連線設定',
        mech_sub: '多重金鑰系統',
        mech_hide_ep: '[ 通道網址 ]',
        mech_edit_ep: '[ 編輯網址 ]',
        btn_export_json: '匯出設定檔 (JSON)',
        btn_import_json: '匯入設定檔 (JSON)',
        msg_import_success: '設定匯入成功',
        msg_import_fail: '匯入失敗：格式錯誤或是無效的 JSON 檔',
        prompt_sep_basket: '\n========== [ 採集籃內容 ] ==========\n',
        prompt_item_prefix: '[第 {n} 筆資料 來源: {source}]',
        prompt_end: '\n[上下文結束]',
        prompt_fragment: '--- 對話片段 ---',
        src_manual: '手動輸入 (新筆記)',
        src_drop: ' (拖曳內容)',
        src_file: ' (檔案匯入)',
        src_local: ' (本機檔案)',
        tooltip_transfer_to: '轉移上下文至 {name}',
        tooltip_send_to: '發送此回應到 {name}',
        tooltip_send_all_to: '將所有面板回應發送到 {name}',
        overlay_drop_add: '放開以加入採集籃',
        overlay_acquiring: '數據擷取中...',
        sys_btn_summary: '📝',
        sys_tooltip_summary: '載入: 重點總結',
        sys_prompt_summary: '請針對以下內容進行總結，列出重點摘要與結論：',
        sys_btn_translate: '🌐',
        sys_tooltip_translate: '載入: 翻譯成繁中',
        sys_prompt_translate: '請將以下內容翻譯成流暢、專業的繁體中文：',
        sys_btn_explain: '💡',
        sys_tooltip_explain: '載入: 白話解釋',
        sys_prompt_explain: '請用簡單易懂的方式解釋以下內容：',
        sys_btn_custom_add: '➕',
        sys_btn_custom_user: '👤',
        sys_tooltip_custom_empty: '儲存目前 Prompt 為自訂模板',
        sys_tooltip_custom_saved: '左鍵: 載入自訂模板\nShift+左鍵: 覆蓋儲存目前內容',
        toast_custom_saved: '自訂 Prompt 已儲存 ✨',
        sys_btn_save: '💾',
        sys_tooltip_save: '儲存/管理 自訂 Prompt (最多3組)',
        sys_tooltip_load: '載入自訂 Prompt',
        prompt_save_title: '儲存自訂 Prompt',
        prompt_save_name_ph: '輸入名稱 (例如: 翻譯助手)',
        prompt_save_btn_new: '新增儲存',
        prompt_save_btn_overwrite: '覆蓋選取項目',
        prompt_save_limit: '已達上限 (3組)，請選擇項目進行覆蓋',
        prompt_load_empty: '尚未儲存任何 Prompt',
        prompt_toast_saved: 'Prompt 已儲存 ✨',
        drone_title: '拖曳文字至此儲存 / 點擊開啟 Context-Carry',
        drone_dismiss: '在此網站隱藏 (直到點擊擴充功能圖示)',
        mm_title_single: '🤖 AI 回應',
        mm_title_multi: '⚡ 工作流引擎 (Workflow)',
        mm_view_multi: '🔀 切換多節點視圖',
        mm_view_single: '⏹ 切換單一視圖',
        mm_loop_label: '迴圈:',
        mm_add_node: '+ 節點',
        mm_run: '▶ 執行',
        mm_stop: '⏹ 中止',
        mm_basket: '🧺 採集籃',
        mm_basket_paste: '📥 貼至所有節點',
        mm_basket_export: '⬇️ 匯出籃子',
        mm_basket_import: '⬆️ 匯入籃子',
        mm_send_all: '🚀 貼到所有平台',
        mm_basket_tip_drop: '放開以加入採集籃',
        mm_basket_added: '已加入採集籃',
        mm_basket_empty: '採集籃是空的',
        mm_basket_paste_all: '📥 貼至所有節點',
        mm_node_edit: '編輯',
        mm_node_clear: '清空',
        mm_node_copy: '複製',
        mm_node_drag: '拖曳內容',
        mm_node_run: '執行此節點',
        mm_save_txt: '存為 .txt',
        mm_save_md: '存為 .md',
        mm_confirm_del_conn: '刪除連線?',
        mm_confirm_clear: '確定清空內容?',
        pip_tab_collect: '📥 收集箱',
        pip_tab_flow: '⚡ 工作流',
        pip_drop_title: '放開以匯入',
        pip_drop_sub: '(支援檔案、文字、程式碼)',
        pip_tooltip_theme: '切換主題',
        pip_tooltip_settings: '設定',
        pip_tooltip_max: '最大化/還原',
        pip_btn_paste: '貼上',
        pip_btn_export: '匯出',
        pip_btn_clear: '清空',
        pip_empty_list: '目前沒有資料',
        pip_basket_title: '🧺 採集籃',
        pip_basket_empty: '空空如也',
        pip_tag_all: '全部',
        pip_node_idle: '閒置',
        pip_node_running: '執行中',
        pip_node_done: '完成',
        pip_node_error: '錯誤',
        pip_node_ph: '等待輸入...',
        pip_node_no_config: '無設定',
        pip_tooltip_run_node: '執行此節點',
        pip_tooltip_edit_node: '編輯內容',
        pip_tooltip_del_node: '刪除節點',
        pip_modal_clear_title: '清空採集籃',
        pip_modal_clear_msg: '確定要刪除所有項目嗎？此動作無法復原。',
        pip_modal_confirm: '確認清空',
        pip_modal_cancel: '取消',
        pip_export_title: '匯出採集籃',
        pip_label_filename: '檔案名稱',
        pip_label_format: '匯出格式',
        pip_btn_save_export: '匯出 / 儲存',
        pip_toast_pasted: '已從剪貼簿貼上 ✨',
        pip_toast_empty: '剪貼簿是空的',
        pip_toast_perm: '需要權限 (請先點擊視窗內部)',
        pip_toast_cleared: '採集籃已清空 🗑️',
        pip_confirm_del_item: '刪除',
        robot_comms_tab: '通訊',
        drone_cargo: '收集',
        hint_drag: ' (拖曳)',
        toast_input_not_found: '未偵測到輸入框，內容已複製到剪貼簿 📋',
        toast_file_too_large: '❌ 檔案太大: {name} ({size}MB). 上限 10MB.',
        toast_file_loaded: '檔案已載入: {name}',
        toast_manual_add_source: '手動輸入',
        btn_ping: '拖曳釘選位置',
        btn_qrcode: '生成 QR Code',
        btn_pip: '打開獨立視窗 (PiP)',
        btn_switch_ui_robot: '切換機甲風格',
        emptyMsg: '[ 貨艙清空中 ]'
    },
    'en': {
        title: 'ContextCarry',
        status_ready: 'Ready',
        status_scanning: 'Scanning...',
        label_prefix: '[System Prompt]:',
        placeholder: 'Enter instructions for the AI here...',
        btn_scan: 'Rescan Page',
        btn_select_all: 'Select All',
        btn_unselect_all: 'Unselect All',
        btn_scan_done: 'Scanned',
        btn_dl: 'Export Basket',
        btn_copy: 'Copy to Clipboard',
        label_transfer: 'Transfer to (Cross-LLM):',
        msg_detected: 'Detected {n} messages',
        msg_selected: 'Selected: {n}',
        alert_no_selection: 'Please select messages or add to basket first!',
        alert_copy_done: 'Content copied!',
        alert_fail: 'Operation failed. Check permissions.',
        btn_add_title: 'Add this block (Shift for range)',
        toast_autofill: 'Context-Carry: Content Auto-filled.',
        default_prompt: `Please summarize the following content, highlighting key points and conclusions:`,
        label_basket: '🧺 Context Basket:',
        btn_add_basket: 'Add (+)',
        btn_clear_basket: 'Clear',
        btn_paste_basket: 'Paste Here',
        basket_status: '{n} items in basket (Click to View ▼)',
        basket_status_empty: 'Basket is empty',
        toast_basket_add: 'Added to Basket 🧺',
        toast_basket_clear: 'Basket Cleared 🗑️',
        preview_del_tooltip: 'Remove item',
        preview_drag_hint: 'Drag to reorder ⇅ (Hover for details)',
        token_est: '📊 Est. Tokens:',
        token_warn_title: '⚠️ Token Limit Warning',
        token_warn_msg: 'Content ({est}) exceeds recommended limit for {platform} ({limit}).\n\nTransferring may cause memory loss.\nDo you want to proceed?',
        btn_paint: '🖌️ Select',
        paint_tooltip: 'Select area of text',
        toast_enter_paint: 'Entered selection mode (Press ESC to exit)',
        paint_no_text: 'No text selected',
        preview_title: '📝 <b>Confirm selection (Preview)</b>',
        preview_words: 'Chars',
        preview_cancel: 'Cancel',
        preview_confirm: 'Add to Basket',
        source_area_select: ' (Area Select)',
        alert_llm_only: 'Auto-fill is only available on supported(ChatGPT, Claude, Gemini, Grok)',
        btn_summary: 'AI Summary',
        btn_new_doc: 'New Doc',
        enter_new_doc: 'Enter content',
        ai_settings_title: 'AI Settings',
        ai_settings_endpoint: 'API Endpoint',
        ai_settings_api_key: 'API Key',
        ai_settings_save: 'Save Settings',
        ai_unconfigured: 'AI is not configured yet. Please set it up.',
        ai_response_title: 'AI Response',
        ai_response_tab_response: 'Response',
        ai_response_tab_context: 'Context',
        ai_summary_sending: 'Summarizing...',
        ai_summary_error: 'Summarization failed',
        drawer_toggle: 'Advanced & Basket',
        ai_setting_tab: 'AI Settings',
        ai_response_tab: 'AI Response',
        ai_config_title: 'AI Configuration',
        ai_provider: 'Provider',
        ai_api_key: 'API Key',
        ai_model: 'Model Name',
        ai_endpoint_toggle: 'Advanced Endpoint',
        ai_save: 'Save Settings',
        ai_modal_title: 'AI Response',
        ai_modal_processing: 'AI Processing...',
        ai_modal_done: '✅ AI Done',
        ai_tab_res: 'Response',
        ai_tab_ctx: 'Sent Context (Edit)',
        btn_resend: '🔄 Re-send with edited context',
        btn_save_file: '⬇️ Save',
        btn_paste: '📋 Paste to Window',
        btn_send_all: '🚀 Paste to All',
        btn_copy_res: 'Copy',
        btn_clear_res: 'Clear',
        btn_min_restore: 'Restore',
        btn_lang_title: 'Switch Language',
        btn_theme_title: 'Toggle Dark Mode',
        btn_close_title: 'Close Panel',
        hint_shortcut_lang: ' (Alt+L)',
        hint_shortcut_paint: ' (Alt+C)',
        hint_shortcut_toggle: ' (Alt+M)',
        btn_switch_ui: 'Switch UI Style',
        hatch_expand: '▼ DEPLOY BASKET',
        hatch_retract: '▲ RETRACT BASKET',
        btn_quick_settings: '⚙️ AI Settings',
        unlock_title: '🔒 ENABLE AI FEATURES',
        unlock_warning: `⚠️ <b>IMPORTANT: AI Features operate under a "Bring Your Own Key" (BYO Key) model.</b>
<br/><br/>
<ul>
    <li><b>Key Control:</b> Your provided API keys are <b>stored exclusively in your browser's local storage</b>.</li><br/><br/>
    <li><b>Data Privacy:</b> All context content <b>is NEVER transmitted to any servers belonging to Context-Carry's developers</b>. All AI requests are sent directly from your browser to the third-party LLM provider you select.</li><br/><br/>
    <li><b>User Costs:</b> These LLM services are <b>NOT FREE</b> and will charge your account based on your usage.</li>
</ul>
<br/>
By enabling this feature, you <b>fully acknowledge</b> and agree to use your own keys, assuming all associated costs and liabilities with the third-party service.`,
        unlock_cancel: 'CANCEL',
        unlock_confirm: 'I UNDERSTAND, ENABLE AI',
        unlock_enabling: 'ENABLING...',
        unlock_toast_success: 'AI Features Enabled 🔓',
        ai_panel_active: 'ACTIVATE PANEL {n}',
        ai_panel_empty_title: 'Waiting for Input',
        ai_panel_empty_msg: 'Please add content in the <span id="goto-edit-{n}" style="color:#00d2ff; cursor:pointer; text-decoration:underline;">Edit Tab</span>',
        ai_panel_status_ready: 'Ready. Click 🚀 to start.',
        ai_panel_copy_tooltip: 'Copy Response',
        ai_panel_close_tooltip: 'Deactivate Panel',
        ai_panel_not_activated: 'PANEL {n} NOT ACTIVATED',
        ai_import_basket_tooltip: 'Import Basket Content',
        ai_copy_ctx_tooltip: 'Copy this context',
        ai_ctx_placeholder: 'Enter context here...',
        ai_save_indicator_saving: 'Saving...',
        ai_save_indicator_saved: 'Saved ✓',
        label_load_profile: 'LOAD PROFILE',
        label_config_name: 'CONFIG NAME',
        label_ai_provider: 'AI PROVIDER',
        label_api_key: 'API KEY',
        label_target_model: 'TARGET MODEL',
        label_endpoint: 'API ENDPOINT',
        option_new_profile: '-- Create New --',
        option_loading: 'Loading...',
        btn_align: '🔁 Align All',
        btn_align_tooltip: 'Copy context from Panel {n} to ALL panels',
        msg_align_confirm: 'Copy context from Panel {n} to all other panels?',
        btn_apply_view: 'Apply & View >>',
        btn_start_all: '⚡ Start All',
        btn_copy_all_res: '📋 Copy All',
        warn_resource_title: '⚠️ RESOURCE WARNING',
        warn_resource_msg1: 'Activating Multi-Node View (10 Nodes).',
        warn_resource_msg2: 'This launches 3 simultaneous AI requests.',
        warn_resource_msg3: 'Ensure you have set API keys for all panels.',
        btn_proceed: 'PROCEED',
        btn_abort: 'ABORT',
        msg_no_ready_panels: 'No ready panels (Check content/settings)',
        msg_all_copied: 'All responses copied!',
        msg_context_synced: 'Context synced',
        msg_imported_basket: 'Imported {n} items to Panel {i}',
        msg_basket_empty: 'Basket is empty!',
        ph_config_name: 'e.g. My GPT-4 Work',
        ph_api_key: 'sk-...',
        ph_model: 'e.g. gpt-4o-mini',
        ai_panel_resend: 'Start / Resend',
        btn_layout_single: 'Single View',
        btn_layout_quad: 'Quad View',
        mech_header: '// NEURAL UPLINK CONFIG',
        mech_sub: 'MULTI-KEY SYSTEM',
        mech_hide_ep: '[ HIDE ENDPOINT ]',
        mech_edit_ep: '[ EDIT ENDPOINT ]',
        btn_export_json: 'Export Config (JSON)',
        btn_import_json: 'Import Config (JSON)',
        msg_import_success: 'Configuration imported successfully',
        msg_import_fail: 'Import failed: Invalid format or JSON',
        prompt_sep_basket: '\n========== [ BASKET CONTENT ] ==========\n',
        prompt_item_prefix: '[Basket Item {n} from {source}]',
        prompt_end: '\n[END OF CONTEXT]',
        prompt_fragment: '--- Fragment ---',
        src_manual: 'Manual Entry (New Doc)',
        src_drop: ' (Drag & Drop)',
        src_file: ' (File)',
        src_local: ' (Local File)',
        tooltip_transfer_to: 'Transfer Context to {name}',
        tooltip_send_to: 'Send this response to {name}',
        tooltip_send_all_to: 'Send all responses to {name}',
        overlay_drop_add: 'Drop to Add to Basket',
        overlay_acquiring: 'ACQUIRING DATA...',
        sys_btn_summary: '📝',
        sys_tooltip_summary: 'Load: Summary',
        sys_prompt_summary: 'Please summarize the following content, highlighting key points and conclusions:',
        sys_btn_translate: '🌐',
        sys_tooltip_translate: 'Load: Translate',
        sys_prompt_translate: 'Please translate the following content into professional English:',
        sys_btn_explain: '💡',
        sys_tooltip_explain: 'Load: Explain',
        sys_prompt_explain: 'Please explain the following content in simple terms:',
        sys_btn_custom_add: '➕',
        sys_btn_custom_user: '👤',
        sys_tooltip_custom_empty: 'Save current prompt as custom',
        sys_tooltip_custom_saved: 'Click: Load Custom\nShift+Click: Overwrite Save',
        toast_custom_saved: 'Custom Prompt Saved ✨',
        sys_btn_save: '💾',
        sys_tooltip_save: 'Save/Manage Custom Prompts (Max 3)',
        sys_tooltip_load: 'Load Custom Prompt',
        prompt_save_title: 'Save Custom Prompt',
        prompt_save_name_ph: 'Enter Name (e.g. My Helper)',
        prompt_save_btn_new: 'Save as New',
        prompt_save_btn_overwrite: 'Overwrite Selected',
        prompt_save_limit: 'Limit Reached (3), please overwrite.',
        prompt_load_empty: 'No saved prompts',
        prompt_toast_saved: 'Prompt Saved ✨',
        drone_title: 'Drag text here to save / Click to open Context-Carry',
        drone_dismiss: 'Don\'t show on this site until I click the extension icon',
        mm_title_single: '🤖 AI Response',
        mm_title_multi: '⚡ Workflow Engine',
        mm_view_multi: '🔀 Multi-Node View',
        mm_view_single: '⏹ Single View',
        mm_loop_label: 'Loop:',
        mm_add_node: '+ Node',
        mm_run: '▶ Run',
        mm_stop: '⏹ ABORT',
        mm_basket: '🧺 Basket',
        mm_basket_paste: '📥 Paste to All',
        mm_basket_export: '⬇️ Export Basket',
        mm_basket_import: '⬆️ Import Basket',
        mm_send_all: '🚀 NewTab to All',
        mm_basket_tip_drop: 'Drop to Add',
        mm_basket_added: 'Added to Basket',
        mm_basket_empty: 'Basket is empty',
        mm_basket_paste_all: '📥 Paste to All',
        mm_node_edit: 'Edit',
        mm_node_clear: 'Clear',
        mm_node_copy: 'Copy',
        mm_node_drag: 'Drag Content',
        mm_node_run: 'Run Node',
        mm_save_txt: 'Save .txt',
        mm_save_md: 'Save .md',
        mm_confirm_del_conn: 'Delete connection?',
        mm_confirm_clear: 'Clear content?',
        pip_tab_collect: '📥 COLLECTOR',
        pip_tab_flow: '⚡ WORKFLOW',
        pip_drop_title: 'DROP TO IMPORT',
        pip_drop_sub: '(Files, Text, Code)',
        pip_tooltip_theme: 'Toggle Theme',
        pip_tooltip_settings: 'Settings',
        pip_tooltip_max: 'Maximize/Restore',
        pip_btn_paste: 'Paste',
        pip_btn_export: 'Export',
        pip_btn_clear: 'Clear',
        pip_empty_list: 'No items found.',
        pip_basket_title: '🧺 BASKET',
        pip_basket_empty: 'Empty',
        pip_tag_all: 'All',
        pip_node_idle: 'IDLE',
        pip_node_running: 'RUNNING',
        pip_node_done: 'DONE',
        pip_node_error: 'ERROR',
        pip_node_ph: 'Waiting for input...',
        pip_node_no_config: 'No Config',
        pip_tooltip_run_node: 'Run Node',
        pip_tooltip_edit_node: 'Edit Content',
        pip_tooltip_del_node: 'Delete Node',
        pip_modal_clear_title: 'Clear Basket',
        pip_modal_clear_msg: 'Are you sure you want to remove all items? This action cannot be undone.',
        pip_modal_confirm: 'Confirm',
        pip_modal_cancel: 'Cancel',
        pip_export_title: 'EXPORT BASKET',
        pip_label_filename: 'FILE NAME',
        pip_label_format: 'FORMAT',
        pip_btn_save_export: 'EXPORT / SAVE',
        pip_toast_pasted: 'Pasted from Clipboard ✨',
        pip_toast_empty: 'Clipboard is empty',
        pip_toast_perm: 'Permission required (Click window first)',
        pip_toast_cleared: 'Basket Cleared 🗑️',
        pip_confirm_del_item: 'Delete',
        robot_comms_tab: 'COMMS',
        drone_cargo: 'Cargo',
        hint_drag: ' (Drag)',
        toast_input_not_found: 'No input field detected. Copied to clipboard 📋',
        toast_file_too_large: '❌ File too large: {name} ({size}MB). Max 10MB.',
        toast_file_loaded: 'File loaded: {name}',
        toast_manual_add_source: 'Manual Entry',
        btn_ping: 'Drag to Pin',
        btn_qrcode: 'Generate QR Code',
        btn_pip: 'Open Independent Window (PiP)',
        btn_switch_ui_robot: 'Switch to Robot UI',
        emptyMsg: '[ CARGO BAY EMPTY ]'
    },
    'zh-CN': {
        title: 'ContextCarry',
        status_ready: '准备就绪',
        status_scanning: '正在扫描...',
        label_prefix: '自定义前缀提示词:',
        placeholder: '在此输入要给 AI 的引导指令...',
        btn_scan: '重新扫描页面',
        btn_scan_done: '已重新扫描',
        btn_select_all: '全选所有消息',
        btn_unselect_all: '取消全选',
        btn_dl: '导出采集篮',
        btn_copy: '复制到剪贴板',
        label_transfer: '转移并打开 (Cross-LLM):',
        msg_detected: '检测到 {n} 条消息',
        msg_selected: '已选中: {n} 条',
        alert_no_selection: '请先选择对话或加入采集篮！',
        alert_copy_done: '内容已复制！',
        alert_fail: '操作失败，请检查权限',
        btn_add_title: '加入此段落 (Shift 可连选)',
        toast_autofill: 'Context-Carry: 已自动填充内容.',
        default_prompt: `请针对以下内容进行总结，列出重点摘要与结论：`,
        label_basket: '🧺 跨窗口采集篮 (Basket):',
        btn_add_basket: '加入 (+)',
        btn_clear_basket: '清空',
        btn_paste_basket: '填入当前窗口',
        basket_status: '当前有 {n} 条数据 (点击预览 ▼)',
        basket_status_empty: '采集篮为空',
        toast_basket_add: '已加入采集篮 🧺',
        toast_basket_clear: '采集篮已清空 🗑️',
        preview_del_tooltip: '删除此条数据',
        preview_drag_hint: '可拖拽排序 ⇅ (悬停可看详情)',
        token_est: '📊 预估 Token:',
        token_warn_title: '⚠️ Token 数量警告',
        token_warn_msg: '预估内容 ({est}) 超过了 {platform} 的建议限制 ({limit})。\n\n强行转移可能会导致记忆丢失。\n是否仍要继续？',
        btn_paint: '🖌️ 圈选',
        paint_tooltip: '圈选画面区域文字',
        toast_enter_paint: '进入圈选模式 (按 ESC 退出)',
        paint_no_text: '未选中任何文字',
        preview_title: '📝 <b>确认获取内容 (Preview)</b>',
        preview_words: '字数',
        preview_cancel: '取消',
        preview_confirm: '加入采集',
        source_area_select: ' (圈选)',
        alert_llm_only: '自动填充功能 (Auto-fill) 仅支持(ChatGPT, Claude, Gemini, Grok)',
        btn_summary: 'AI 总结',
        btn_new_doc: '新建笔记',
        enter_new_doc: '请输入内容：',
        ai_settings_title: 'AI 设置',
        ai_settings_endpoint: 'API 地址 (Endpoint)',
        ai_settings_api_key: 'API 密钥 (Key)',
        ai_settings_save: '保存设置',
        ai_unconfigured: '尚未设置 AI，请先进行配置。',
        ai_response_title: 'AI 回应',
        ai_response_tab_response: '回应',
        ai_response_tab_context: '上下文',
        ai_summary_sending: 'AI 正在总结中...',
        ai_summary_error: 'AI 请求失败',
        drawer_toggle: '高级选项 & 采集篮',
        ai_setting_tab: 'AI 设置',
        ai_response_tab: 'AI 回应',
        ai_config_title: 'AI 设置',
        ai_provider: '模型供应商 (Provider)',
        ai_api_key: 'API 密钥 (Key)',
        ai_model: '模型名称 (Model)',
        ai_endpoint_toggle: 'API 地址 (Endpoint)',
        ai_save: '保存设置',
        ai_modal_title: 'AI 回应',
        ai_modal_processing: 'AI 思考中...',
        ai_modal_done: '✅ 完成',
        ai_tab_res: 'AI 回应',
        ai_tab_ctx: '发送内容 (编辑)',
        btn_resend: '🔄 更新内容并重试',
        btn_save_file: '⬇️ 存为文件',
        btn_paste: '📋 填入当前窗口',
        btn_send_all: '🚀 贴到全部',
        btn_copy_res: '复制',
        btn_clear_res: '清空',
        btn_min_restore: '还原窗口',
        btn_lang_title: '切换语言',
        btn_theme_title: '切换深色模式',
        btn_close_title: '关闭面板',
        hint_shortcut_lang: ' (Alt+L)',
        hint_shortcut_paint: ' (Alt+C)',
        hint_shortcut_toggle: ' (Alt+M)',
        btn_switch_ui: '切换界面风格',
        hatch_expand: '▼ 展开货舱',
        hatch_retract: '▲ 收起货舱',
        btn_quick_settings: '⚙️ AI 设置',
        unlock_title: '🔒 启用 AI 功能',
        unlock_warning: `⚠️ <b>重要：AI功能采用“自备密钥-BYO Key”模式。</b>
<br/><br/>
<ul>
    <li><b>密钥由您控制：</b>您提供的 API 密钥<b>仅存储在您浏览器的本地存储空间</b>中。</li><br/><br/>
    <li><b>数据保持本地：</b>所有内容<b>绝不会被传输到 Context-Carry 开发者的任何服务器</b>。所有 AI 请求都是从您的浏览器直接发送到您选择的第三方 LLM 供应商。</li><br/><br/>
    <li><b>费用由您承担：</b>这些 LLM 服务<b>不是免费的</b>，将根据您的密钥和使用量向您的账户收取费用。</li>
</ul>
<br/>
启用此功能，即表示您<b>完全知情</b>并同意使用您自己的密钥，并由您自行承担所有第三方服务费用。`,
        unlock_cancel: '取消',
        unlock_confirm: '我了解，启用 AI',
        unlock_enabling: '启用中...',
        unlock_toast_success: 'AI 功能已启用 🔓',
        ai_panel_active: '启用面板 {n}',
        ai_panel_empty_title: '等待输入',
        ai_panel_empty_msg: '<span id="goto-edit-{n}" style="color:#00d2ff; cursor:pointer; text-decoration:underline;">编辑</span> 加入内容',
        ai_panel_status_ready: '就绪。点击 🚀 开始。',
        ai_panel_copy_tooltip: '复制回应',
        ai_panel_close_tooltip: '停用面板',
        ai_panel_not_activated: '面板 {n} 未启用',
        ai_import_basket_tooltip: '导入采集篮内容',
        ai_copy_ctx_tooltip: '复制此内容',
        ai_ctx_placeholder: '在此输入上下文...',
        ai_save_indicator_saving: '保存中...',
        ai_save_indicator_saved: '已保存 ✓',
        label_load_profile: '读取配置文件',
        label_config_name: '配置名称 (Alias)',
        label_ai_provider: '模型供应商 (Provider)',
        label_api_key: 'API 密钥 (Key)',
        label_target_model: '目标模型 (Model)',
        label_endpoint: 'API 地址 (Endpoint)',
        option_new_profile: '-- 建立新配置 --',
        option_loading: '加载中...',
        btn_align: '🔁 同步全部',
        btn_align_tooltip: '将面板 {n} 的内容复制到“所有”面板',
        msg_align_confirm: '确定要将面板 {n} 的内容复制覆盖到其他所有面板吗？',
        btn_apply_view: '应用并查看 >>',
        btn_start_all: '⚡ 全部开始',
        btn_copy_all_res: '📋 复制全部',
        warn_resource_title: '⚠️ 资源消耗警告',
        warn_resource_msg1: '即将启用多节点视图 (Multi-Node View)。',
        warn_resource_msg2: '这将最多同时发送 3 个 AI 请求。',
        warn_resource_msg3: '请确认所有面板皆已设置 API Key，以免产生意外费用或错误。',
        btn_proceed: '继续执行',
        btn_abort: '取消',
        msg_no_ready_panels: '没有准备就绪的面板 (请检查内容或设置)',
        msg_all_copied: '已复制所有回应！',
        msg_context_synced: '上下文已同步',
        msg_imported_basket: '已导入 {n} 条数据至面板 {i}',
        msg_basket_empty: '采集篮为空！',
        ph_config_name: '例如: 工作用',
        ph_api_key: 'sk-...',
        ph_model: '例如: gpt-4o-mini',
        ai_panel_resend: '开始 / 重试',
        btn_layout_single: '单页模式',
        btn_layout_quad: '多页模式',
        mech_header: '// 神经网络连接设置',
        mech_sub: '多重密钥系统',
        mech_hide_ep: '[ 通道地址 ]',
        mech_edit_ep: '[ 编辑地址 ]',
        btn_export_json: '导出配置文件 (JSON)',
        btn_import_json: '导入配置文件 (JSON)',
        msg_import_success: '配置导入成功',
        msg_import_fail: '导入失败：格式错误或是无效的 JSON 文件',
        prompt_sep_basket: '\n========== [ 采集篮内容 ] ==========\n',
        prompt_item_prefix: '[第 {n} 条数据 来源: {source}]',
        prompt_end: '\n[上下文结束]',
        prompt_fragment: '--- 对话片段 ---',
        src_manual: '手动输入 (新笔记)',
        src_drop: ' (拖拽内容)',
        src_file: ' (文件导入)',
        src_local: ' (本地文件)',
        tooltip_transfer_to: '转移上下文至 {name}',
        tooltip_send_to: '发送此回应到 {name}',
        tooltip_send_all_to: '将所有面板回应发送到 {name}',
        overlay_drop_add: '松开以加入采集篮',
        overlay_acquiring: '数据获取中...',
        sys_btn_summary: '📝',
        sys_tooltip_summary: '加载: 重点总结',
        sys_prompt_summary: '请针对以下内容进行总结，列出重点摘要与结论：',
        sys_btn_translate: '🌐',
        sys_tooltip_translate: '加载: 翻译成中文',
        sys_prompt_translate: '请将以下内容翻译成流畅、专业的简体中文：',
        sys_btn_explain: '💡',
        sys_tooltip_explain: '加载: 白话解释',
        sys_prompt_explain: '请用简单易懂的方式解释以下内容：',
        sys_btn_custom_add: '➕',
        sys_btn_custom_user: '👤',
        sys_tooltip_custom_empty: '保存当前 Prompt 为自定义模板',
        sys_tooltip_custom_saved: '左键: 加载自定义模板\nShift+左键: 覆盖保存当前内容',
        toast_custom_saved: '自定义 Prompt 已保存 ✨',
        sys_btn_save: '💾',
        sys_tooltip_save: '保存/管理 自定义 Prompt (最多3组)',
        sys_tooltip_load: '加载自定义 Prompt',
        prompt_save_title: '保存自定义 Prompt',
        prompt_save_name_ph: '输入名称 (例如: 翻译助手)',
        prompt_save_btn_new: '新增保存',
        prompt_save_btn_overwrite: '覆盖所选项',
        prompt_save_limit: '已达上限 (3组)，请选择项目进行覆盖',
        prompt_load_empty: '尚未保存任何 Prompt',
        prompt_toast_saved: 'Prompt 已保存 ✨',
        drone_title: '拖拽文字至此保存 / 点击开启 Context-Carry',
        drone_dismiss: '在此网站隐藏 (直到点击扩展图标)',
        mm_title_single: '🤖 AI 回应',
        mm_title_multi: '⚡ 工作流引擎 (Workflow)',
        mm_view_multi: '🔀 切换多节点视图',
        mm_view_single: '⏹ 切换单一视图',
        mm_loop_label: '循环:',
        mm_add_node: '+ 节点',
        mm_run: '▶ 执行',
        mm_stop: '⏹ 中止',
        mm_basket: '🧺 采集篮',
        mm_basket_paste: '📥 贴至所有节点',
        mm_basket_export: '⬇️ 导出篮子',
        mm_basket_import: '⬆️ 导入篮子',
        mm_send_all: '🚀 贴到所有平台',
        mm_basket_tip_drop: '松开以加入采集篮',
        mm_basket_added: '已加入采集篮',
        mm_basket_empty: '采集篮为空',
        mm_basket_paste_all: '📥 贴至所有节点',
        mm_node_edit: '编辑',
        mm_node_clear: '清空',
        mm_node_copy: '复制',
        mm_node_drag: '拖拽内容',
        mm_node_run: '执行此节点',
        mm_save_txt: '存为 .txt',
        mm_save_md: '存为 .md',
        mm_confirm_del_conn: '删除连线?',
        mm_confirm_clear: '确定清空内容?',
        pip_tab_collect: '📥 收集箱',
        pip_tab_flow: '⚡ 工作流',
        pip_drop_title: '松开以导入',
        pip_drop_sub: '(支持文件、文字、代码)',
        pip_tooltip_theme: '切换主题',
        pip_tooltip_settings: '设置',
        pip_tooltip_max: '最大化/还原',
        pip_btn_paste: '粘贴',
        pip_btn_export: '导出',
        pip_btn_clear: '清空',
        pip_empty_list: '目前没有数据',
        pip_basket_title: '🧺 采集篮',
        pip_basket_empty: '空空如也',
        pip_tag_all: '全部',
        pip_node_idle: '空闲',
        pip_node_running: '运行中',
        pip_node_done: '完成',
        pip_node_error: '错误',
        pip_node_ph: '等待输入...',
        pip_node_no_config: '无配置',
        pip_tooltip_run_node: '执行此节点',
        pip_tooltip_edit_node: '编辑内容',
        pip_tooltip_del_node: '删除节点',
        pip_modal_clear_title: '清空采集篮',
        pip_modal_clear_msg: '确定要删除所有项目吗？此动作无法恢复。',
        pip_modal_confirm: '确认清空',
        pip_modal_cancel: '取消',
        pip_export_title: '导出采集篮',
        pip_label_filename: '文件名称',
        pip_label_format: '导出格式',
        pip_btn_save_export: '导出 / 保存',
        pip_toast_pasted: '已从剪贴板粘贴 ✨',
        pip_toast_empty: '剪贴板为空',
        pip_toast_perm: '需要权限 (请先点击窗口内部)',
        pip_toast_cleared: '采集篮已清空 🗑️',
        pip_confirm_del_item: '删除',
        robot_comms_tab: '通讯',
        drone_cargo: '收集',
        hint_drag: ' (拖拽)',
        toast_input_not_found: '未检测到输入框，内容已复制到剪贴板 📋',
        toast_file_too_large: '❌ 文件太大: {name} ({size}MB). 上限 10MB.',
        toast_file_loaded: '文件已加载: {name}',
        toast_manual_add_source: '手动输入',
        btn_ping: '拖拽固定位置',
        btn_qrcode: '生成二维码',
        btn_pip: '打开独立窗口 (PiP)',
        btn_switch_ui_robot: '切换机甲风格',
        emptyMsg: '[ 货舱清空中 ]'
    },
    'ja': {
        title: 'ContextCarry',
        status_ready: '準備完了',
        status_scanning: 'スキャン中...',
        label_prefix: 'カスタム System Prompt:',
        placeholder: 'AI への指示を入力してください...',
        btn_scan: 'ページを再スキャン',
        btn_scan_done: 'スキャン済み',
        btn_select_all: 'すべてのメッセージを選択',
        btn_unselect_all: '選択解除',
        btn_dl: 'バスケットをエクスポート',
        btn_copy: 'クリップボードにコピー',
        label_transfer: '転送して開く (Cross-LLM):',
        msg_detected: '{n} 件のメッセージを検出',
        msg_selected: '選択済み: {n} 件',
        alert_no_selection: '会話を選択するか、バスケットに追加してください！',
        alert_copy_done: 'コピーしました！',
        alert_fail: '操作に失敗しました（権限を確認してください）',
        btn_add_title: 'このブロックを追加 (Shiftで範囲選択)',
        toast_autofill: 'Context-Carry: コンテンツを自動入力しました。',
        default_prompt: `以下の内容を要約し、要点と結論をリストアップしてください：`,
        label_basket: '🧺 収集バスケット (Basket):',
        btn_add_basket: '追加 (+)',
        btn_clear_basket: 'クリア',
        btn_paste_basket: 'ここに貼り付け',
        basket_status: 'バスケットに {n} 件 (プレビュー ▼)',
        basket_status_empty: 'バスケットは空です',
        toast_basket_add: 'バスケットに追加しました 🧺',
        toast_basket_clear: 'バスケットをクリアしました 🗑️',
        preview_del_tooltip: 'この項目を削除',
        preview_drag_hint: 'ドラッグして並べ替え ⇅ (詳細を表示)',
        token_est: '📊 推定トークン:',
        token_warn_title: '⚠️ トークン数警告',
        token_warn_msg: 'コンテンツ ({est}) が {platform} の推奨制限 ({limit}) を超えています。\n\n無理に転送すると記憶が失われる可能性があります。\n続行しますか？',
        btn_paint: '🖌️ 選択',
        paint_tooltip: '画面上のテキスト領域を選択',
        toast_enter_paint: '選択モード (ESCで終了)',
        paint_no_text: 'テキストが選択されていません',
        preview_title: '📝 <b>取得内容の確認 (Preview)</b>',
        preview_words: '文字数',
        preview_cancel: 'キャンセル',
        preview_confirm: '追加',
        source_area_select: ' (領域選択)',
        alert_llm_only: '自動入力 (Auto-fill) は (ChatGPT, Claude, Gemini, Grok) のみ対応しています',
        btn_summary: 'AI 要約',
        btn_new_doc: '新規メモ',
        enter_new_doc: '内容を入力：',
        ai_settings_title: 'AI 設定',
        ai_settings_endpoint: 'API エンドポイント',
        ai_settings_api_key: 'API キー (Key)',
        ai_settings_save: '設定を保存',
        ai_unconfigured: 'AI が未設定です。設定を行ってください。',
        ai_response_title: 'AI レスポンス',
        ai_response_tab_response: 'レスポンス',
        ai_response_tab_context: 'コンテキスト',
        ai_summary_sending: 'AI が要約中...',
        ai_summary_error: 'AI リクエスト失敗',
        drawer_toggle: '詳細 & バスケット',
        ai_setting_tab: 'AI 設定',
        ai_response_tab: 'AI レスポンス',
        ai_config_title: 'AI 設定',
        ai_provider: 'プロバイダー (Provider)',
        ai_api_key: 'API キー (Key)',
        ai_model: 'モデル名 (Model)',
        ai_endpoint_toggle: 'API エンドポイント',
        ai_save: '設定を保存',
        ai_modal_title: 'AI レスポンス',
        ai_modal_processing: 'AI 思考中...',
        ai_modal_done: '✅ 完了',
        ai_tab_res: 'AI レスポンス',
        ai_tab_ctx: '送信コンテキスト (編集)',
        btn_resend: '🔄 更新して再試行',
        btn_save_file: '⬇️ 保存',
        btn_paste: '📋 ウィンドウに入力',
        btn_send_all: '🚀 すべてに送信',
        btn_copy_res: 'コピー',
        btn_clear_res: 'クリア',
        btn_min_restore: '元に戻す',
        btn_lang_title: '言語切り替え',
        btn_theme_title: 'ダークモード切替',
        btn_close_title: 'パネルを閉じる',
        hint_shortcut_lang: ' (Alt+L)',
        hint_shortcut_paint: ' (Alt+C)',
        hint_shortcut_toggle: ' (Alt+M)',
        btn_switch_ui: 'UIスタイル切替',
        hatch_expand: '▼ 貨物室を開く',
        hatch_retract: '▲ 貨物室を閉じる',
        btn_quick_settings: '⚙️ AI 設定',
        unlock_title: '🔒 AI機能を有効化',
        unlock_warning: `⚠️ <b>重要：AI機能は「BYO Key（キー持ち込み）」モデルを採用しています。</b>
<br/><br/>
<ul>
    <li><b>キーの管理：</b>提供されたAPIキーは<b>ブラウザのローカルストレージにのみ保存</b>されます。</li><br/><br/>
    <li><b>データプライバシー：</b>コンテンツが<b>Context-Carry開発者のサーバーに送信されることは決してありません</b>。すべてのAIリクエストは、ブラウザから直接、選択したサードパーティLLMプロバイダーに送信されます。</li><br/><br/>
    <li><b>コスト負担：</b>これらのLLMサービスは<b>無料ではなく</b>、使用量に応じてアカウントに請求されます。</li>
</ul>
<br/>
この機能を有効にすると、独自キーを使用することに<b>完全に同意</b>し、サードパーティサービスの費用を自己負担することを承諾したとみなされます。`,
        unlock_cancel: 'キャンセル',
        unlock_confirm: '理解して有効化',
        unlock_enabling: '有効化中...',
        unlock_toast_success: 'AI機能が有効になりました 🔓',
        ai_panel_active: 'パネル {n} を有効化',
        ai_panel_empty_title: '入力待ち',
        ai_panel_empty_msg: '<span id="goto-edit-{n}" style="color:#00d2ff; cursor:pointer; text-decoration:underline;">編集タブ</span> でコンテンツを追加',
        ai_panel_status_ready: '準備完了。 🚀 で開始。',
        ai_panel_copy_tooltip: 'レスポンスをコピー',
        ai_panel_close_tooltip: 'パネルを無効化',
        ai_panel_not_activated: 'パネル {n} は無効です',
        ai_import_basket_tooltip: 'バスケットの内容をインポート',
        ai_copy_ctx_tooltip: 'コンテキストをコピー',
        ai_ctx_placeholder: 'ここにコンテキストを入力...',
        ai_save_indicator_saving: '保存中...',
        ai_save_indicator_saved: '保存済み ✓',
        label_load_profile: 'プロファイル読込',
        label_config_name: '設定名 (Alias)',
        label_ai_provider: 'プロバイダー (Provider)',
        label_api_key: 'API キー (Key)',
        label_target_model: 'ターゲットモデル (Model)',
        label_endpoint: 'API エンドポイント',
        option_new_profile: '-- 新規作成 --',
        option_loading: '読込中...',
        btn_align: '🔁 すべて同期',
        btn_align_tooltip: 'パネル {n} の内容を「すべて」のパネルにコピー',
        msg_align_confirm: 'パネル {n} の内容で他のすべてのパネルを上書きしますか？',
        btn_apply_view: '適用して表示 >>',
        btn_start_all: '⚡ すべて開始',
        btn_copy_all_res: '📋 すべてコピー',
        warn_resource_title: '⚠️ リソース消費警告',
        warn_resource_msg1: 'マルチノードビュー (Multi-Node View) を有効にします。',
        warn_resource_msg2: '最大3つのAIリクエストを同時に送信します。',
        warn_resource_msg3: '予期せぬ費用やエラーを防ぐため、すべてのパネルにAPIキーが設定されていることを確認してください。',
        btn_proceed: '続行',
        btn_abort: '中止',
        msg_no_ready_panels: '準備完了したパネルがありません (内容や設定を確認)',
        msg_all_copied: 'すべてのレスポンスをコピーしました！',
        msg_context_synced: 'コンテキストが同期されました',
        msg_imported_basket: '{n} 件をパネル {i} にインポートしました',
        msg_basket_empty: 'バスケットは空です！',
        ph_config_name: '例: 仕事用',
        ph_api_key: 'sk-...',
        ph_model: '例: gpt-4o-mini',
        ai_panel_resend: '開始 / 再試行',
        btn_layout_single: 'シングルビュー',
        btn_layout_quad: 'マルチビュー',
        mech_header: '// ニューラル接続設定',
        mech_sub: 'マルチキーシステム',
        mech_hide_ep: '[ URLを隠す ]',
        mech_edit_ep: '[ URLを編集 ]',
        btn_export_json: '設定をエクスポート (JSON)',
        btn_import_json: '設定をインポート (JSON)',
        msg_import_success: '設定をインポートしました',
        msg_import_fail: 'インポート失敗：フォーマットエラーまたは無効なJSON',
        prompt_sep_basket: '\n========== [ バスケットの内容 ] ==========\n',
        prompt_item_prefix: '[アイテム {n} 出典: {source}]',
        prompt_end: '\n[コンテキスト終了]',
        prompt_fragment: '--- 会話フラグメント ---',
        src_manual: '手動入力 (新規)',
        src_drop: ' (ドラッグ＆ドロップ)',
        src_file: ' (ファイル)',
        src_local: ' (ローカルファイル)',
        tooltip_transfer_to: '{name} へコンテキスト転送',
        tooltip_send_to: 'このレスポンスを {name} へ送信',
        tooltip_send_all_to: 'すべてのレスポンスを {name} へ送信',
        overlay_drop_add: 'ドロップしてバスケットに追加',
        overlay_acquiring: 'データ取得中...',
        sys_btn_summary: '📝',
        sys_tooltip_summary: '読込: 要約',
        sys_prompt_summary: '以下の内容を要約し、要点と結論をリストアップしてください：',
        sys_btn_translate: '🌐',
        sys_tooltip_translate: '読込: 翻訳 (日)',
        sys_prompt_translate: '以下の内容を自然で専門的な日本語に翻訳してください：',
        sys_btn_explain: '💡',
        sys_tooltip_explain: '読込: 解説',
        sys_prompt_explain: '以下の内容を分かりやすく解説してください：',
        sys_btn_custom_add: '➕',
        sys_btn_custom_user: '👤',
        sys_tooltip_custom_empty: '現在のプロンプトをテンプレートとして保存',
        sys_tooltip_custom_saved: 'クリック: 読込\nShift+クリック: 上書き保存',
        toast_custom_saved: 'カスタムプロンプトを保存しました ✨',
        sys_btn_save: '💾',
        sys_tooltip_save: 'カスタムプロンプトの保存/管理 (最大3つ)',
        sys_tooltip_load: 'カスタムプロンプトを読込',
        prompt_save_title: 'カスタムプロンプト保存',
        prompt_save_name_ph: '名前を入力 (例: 翻訳用)',
        prompt_save_btn_new: '新規保存',
        prompt_save_btn_overwrite: '選択項目を上書き',
        prompt_save_limit: '上限 (3つ) に達しました。上書きしてください。',
        prompt_load_empty: '保存されたプロンプトはありません',
        prompt_toast_saved: 'プロンプトを保存しました ✨',
        drone_title: 'テキストをドラッグして保存 / クリックして Context-Carry を開く',
        drone_dismiss: '拡張機能アイコンをクリックするまで隠す',
        mm_title_single: '🤖 AI レスポンス',
        mm_title_multi: '⚡ ワークフローエンジン',
        mm_view_multi: '🔀 マルチノード表示',
        mm_view_single: '⏹ シングル表示',
        mm_loop_label: 'ループ:',
        mm_add_node: '+ ノード',
        mm_run: '▶ 実行',
        mm_stop: '⏹ 中止',
        mm_basket: '🧺 バスケット',
        mm_basket_paste: '📥 すべてに貼付',
        mm_basket_export: '⬇️ エクスポート',
        mm_basket_import: '⬆️ インポート',
        mm_send_all: '🚀 全PFへ送信',
        mm_basket_tip_drop: 'ドロップして追加',
        mm_basket_added: 'バスケットに追加済',
        mm_basket_empty: 'バスケットは空です',
        mm_basket_paste_all: '📥 すべてに貼付',
        mm_node_edit: '編集',
        mm_node_clear: 'クリア',
        mm_node_copy: 'コピー',
        mm_node_drag: 'コンテンツをドラッグ',
        mm_node_run: 'このノードを実行',
        mm_save_txt: '.txt で保存',
        mm_save_md: '.md で保存',
        mm_confirm_del_conn: '接続を削除しますか?',
        mm_confirm_clear: '内容をクリアしますか?',
        pip_tab_collect: '📥 収集ボックス',
        pip_tab_flow: '⚡ ワークフロー',
        pip_drop_title: 'ドロップしてインポート',
        pip_drop_sub: '(ファイル, テキスト, コード)',
        pip_tooltip_theme: 'テーマ切替',
        pip_tooltip_settings: '設定',
        pip_tooltip_max: '最大化/元に戻す',
        pip_btn_paste: '貼り付け',
        pip_btn_export: 'エクスポート',
        pip_btn_clear: 'クリア',
        pip_empty_list: 'データがありません',
        pip_basket_title: '🧺 バスケット',
        pip_basket_empty: '空です',
        pip_tag_all: 'すべて',
        pip_node_idle: '待機中',
        pip_node_running: '実行中',
        pip_node_done: '完了',
        pip_node_error: 'エラー',
        pip_node_ph: '入力待ち...',
        pip_node_no_config: '未設定',
        pip_tooltip_run_node: 'ノード実行',
        pip_tooltip_edit_node: '内容編集',
        pip_tooltip_del_node: 'ノード削除',
        pip_modal_clear_title: 'バスケットをクリア',
        pip_modal_clear_msg: 'すべての項目を削除しますか？この操作は取り消せません。',
        pip_modal_confirm: '確認',
        pip_modal_cancel: 'キャンセル',
        pip_export_title: 'エクスポート',
        pip_label_filename: 'ファイル名',
        pip_label_format: 'フォーマット',
        pip_btn_save_export: '保存 / エクスポート',
        pip_toast_pasted: 'クリップボードから貼り付けました ✨',
        pip_toast_empty: 'クリップボードは空です',
        pip_toast_perm: '権限が必要です (ウィンドウをクリック)',
        pip_toast_cleared: 'バスケットをクリアしました 🗑️',
        pip_confirm_del_item: '削除',
        robot_comms_tab: '通信',
        drone_cargo: '貨物',
        hint_drag: ' (ドラッグ)',
        toast_input_not_found: '入力欄が見つかりません。クリップボードにコピーしました 📋',
        toast_file_too_large: '❌ ファイルサイズ超過: {name} ({size}MB). 上限 10MB.',
        toast_file_loaded: 'ファイル読込完了: {name}',
        toast_manual_add_source: '手動入力',
        btn_ping: 'ドラッグしてピン留め',
        btn_qrcode: 'QRコード生成',
        btn_pip: '独立ウィンドウ（PiP）',
        btn_switch_ui_robot: '機甲スタイルに切り替え',
        emptyMsg: '[ 貨物室のクリア ]'
    },
    'ko': {
        title: 'ContextCarry',
        status_ready: '준비 완료',
        status_scanning: '스캔 중...',
        label_prefix: '사용자 지정 프롬프트:',
        placeholder: 'AI에게 전달할 지시사항을 입력하세요...',
        btn_scan: '페이지 다시 스캔',
        btn_scan_done: '스캔 완료',
        btn_select_all: '모든 메시지 선택',
        btn_unselect_all: '선택 해제',
        btn_dl: '바스켓 내보내기',
        btn_copy: '클립보드에 복사',
        label_transfer: '전송 및 열기 (Cross-LLM):',
        msg_detected: '{n}개의 메시지 감지',
        msg_selected: '선택됨: {n}개',
        alert_no_selection: '대화를 선택하거나 바스켓에 추가해주세요!',
        alert_copy_done: '내용이 복사되었습니다!',
        alert_fail: '작업 실패. 권한을 확인해주세요.',
        btn_add_title: '이 블록 추가 (Shift로 범위 선택)',
        toast_autofill: 'Context-Carry: 내용이 자동 입력되었습니다.',
        default_prompt: `다음 내용을 요약하고 핵심 사항과 결론을 나열해 주세요:`,
        label_basket: '🧺 수집 바스켓 (Basket):',
        btn_add_basket: '추가 (+)',
        btn_clear_basket: '비우기',
        btn_paste_basket: '여기에 붙여넣기',
        basket_status: '현재 {n}개 항목 (미리보기 ▼)',
        basket_status_empty: '바스켓이 비어있습니다',
        toast_basket_add: '바스켓에 추가됨 🧺',
        toast_basket_clear: '바스켓 비워짐 🗑️',
        preview_del_tooltip: '이 항목 삭제',
        preview_drag_hint: '드래그하여 정렬 ⇅ (마우스 오버시 상세)',
        token_est: '📊 예상 토큰:',
        token_warn_title: '⚠️ 토큰 수 경고',
        token_warn_msg: '예상 내용({est})이 {platform}의 권장 제한({limit})을 초과했습니다.\n\n강제로 전송할 경우 기억 소실이 발생할 수 있습니다.\n계속하시겠습니까?',
        btn_paint: '🖌️ 영역 선택',
        paint_tooltip: '화면 텍스트 영역 선택',
        toast_enter_paint: '선택 모드 진입 (ESC로 종료)',
        paint_no_text: '선택된 텍스트가 없습니다',
        preview_title: '📝 <b>선택 내용 확인 (Preview)</b>',
        preview_words: '글자 수',
        preview_cancel: '취소',
        preview_confirm: '추가',
        source_area_select: ' (영역 선택)',
        alert_llm_only: '자동 입력 기능(Auto-fill)은 (ChatGPT, Claude, Gemini, Grok)만 지원합니다',
        btn_summary: 'AI 요약',
        btn_new_doc: '새 노트',
        enter_new_doc: '내용을 입력하세요:',
        ai_settings_title: 'AI 설정',
        ai_settings_endpoint: 'API 엔드포인트',
        ai_settings_api_key: 'API 키 (Key)',
        ai_settings_save: '설정 저장',
        ai_unconfigured: 'AI가 설정되지 않았습니다. 먼저 설정해주세요.',
        ai_response_title: 'AI 응답',
        ai_response_tab_response: '응답',
        ai_response_tab_context: '컨텍스트',
        ai_summary_sending: 'AI가 요약 중입니다...',
        ai_summary_error: 'AI 요청 실패',
        drawer_toggle: '고급 옵션 & 바스켓',
        ai_setting_tab: 'AI 설정',
        ai_response_tab: 'AI 응답',
        ai_config_title: 'AI 설정',
        ai_provider: '제공자 (Provider)',
        ai_api_key: 'API 키 (Key)',
        ai_model: '모델명 (Model)',
        ai_endpoint_toggle: 'API 엔드포인트',
        ai_save: '설정 저장',
        ai_modal_title: 'AI 응답',
        ai_modal_processing: 'AI 생각 중...',
        ai_modal_done: '✅ 완료',
        ai_tab_res: 'AI 응답',
        ai_tab_ctx: '전송된 컨텍스트 (편집)',
        btn_resend: '🔄 내용 업데이트 및 재시도',
        btn_save_file: '⬇️ 저장',
        btn_paste: '📋 현재 창에 입력',
        btn_send_all: '🚀 모두에게 전송',
        btn_copy_res: '복사',
        btn_clear_res: '비우기',
        btn_min_restore: '창 복원',
        btn_lang_title: '언어 변경',
        btn_theme_title: '다크 모드 전환',
        btn_close_title: '패널 닫기',
        hint_shortcut_lang: ' (Alt+L)',
        hint_shortcut_paint: ' (Alt+C)',
        hint_shortcut_toggle: ' (Alt+M)',
        btn_switch_ui: 'UI 스타일 전환',
        hatch_expand: '▼ 화물칸 열기',
        hatch_retract: '▲ 화물칸 닫기',
        btn_quick_settings: '⚙️ AI 설정',
        unlock_title: '🔒 AI 기능 활성화',
        unlock_warning: `⚠️ <b>중요: AI 기능은 "BYO Key(키 직접 준비)" 모델로 작동합니다.</b>
<br/><br/>
<ul>
    <li><b>키 관리:</b> 입력하신 API 키는 <b>브라우저의 로컬 스토리지에만 저장</b>됩니다.</li><br/><br/>
    <li><b>데이터 보안:</b> 모든 컨텍스트 내용은 <b>Context-Carry 개발자의 서버로 절대 전송되지 않습니다</b>. 모든 AI 요청은 브라우저에서 선택한 타사 LLM 제공업체로 직접 전송됩니다.</li><br/><br/>
    <li><b>비용 부담:</b> 이러한 LLM 서비스는 <b>무료가 아니며</b>, 사용량에 따라 해당 계정으로 비용이 청구됩니다.</li>
</ul>
<br/>
이 기능을 활성화하면 귀하가 자신의 키를 사용한다는 것을 <b>완전히 인지</b>하고, 타사 서비스 비용을 부담하는 것에 동의하는 것으로 간주합니다.`,
        unlock_cancel: '취소',
        unlock_confirm: '이해했습니다, AI 활성화',
        unlock_enabling: '활성화 중...',
        unlock_toast_success: 'AI 기능이 활성화되었습니다 🔓',
        ai_panel_active: '패널 {n} 활성화',
        ai_panel_empty_title: '입력 대기 중',
        ai_panel_empty_msg: '<span id="goto-edit-{n}" style="color:#00d2ff; cursor:pointer; text-decoration:underline;">편집 탭</span>에서 내용을 추가하세요',
        ai_panel_status_ready: '준비 완료. 🚀 클릭하여 시작.',
        ai_panel_copy_tooltip: '응답 복사',
        ai_panel_close_tooltip: '패널 비활성화',
        ai_panel_not_activated: '패널 {n} 비활성',
        ai_import_basket_tooltip: '바스켓 내용 가져오기',
        ai_copy_ctx_tooltip: '이 컨텍스트 복사',
        ai_ctx_placeholder: '여기에 컨텍스트 입력...',
        ai_save_indicator_saving: '저장 중...',
        ai_save_indicator_saved: '저장됨 ✓',
        label_load_profile: '프로필 불러오기',
        label_config_name: '설정 이름 (Alias)',
        label_ai_provider: '제공자 (Provider)',
        label_api_key: 'API 키 (Key)',
        label_target_model: '대상 모델 (Model)',
        label_endpoint: 'API 엔드포인트',
        option_new_profile: '-- 새 설정 만들기 --',
        option_loading: '로딩 중...',
        btn_align: '🔁 모두 동기화',
        btn_align_tooltip: '패널 {n}의 내용을 "모든" 패널로 복사',
        msg_align_confirm: '패널 {n}의 내용으로 다른 모든 패널을 덮어쓰시겠습니까?',
        btn_apply_view: '적용 및 보기 >>',
        btn_start_all: '⚡ 모두 시작',
        btn_copy_all_res: '📋 모두 복사',
        warn_resource_title: '⚠️ 리소스 소모 경고',
        warn_resource_msg1: '다중 노드 뷰(Multi-Node View)를 활성화합니다.',
        warn_resource_msg2: '최대 3개의 AI 요청이 동시에 전송됩니다.',
        warn_resource_msg3: '예상치 못한 비용이나 오류를 방지하기 위해 모든 패널에 API Key가 설정되어 있는지 확인하세요.',
        btn_proceed: '계속 진행',
        btn_abort: '취소',
        msg_no_ready_panels: '준비된 패널이 없습니다 (내용 또는 설정 확인)',
        msg_all_copied: '모든 응답이 복사되었습니다!',
        msg_context_synced: '컨텍스트 동기화됨',
        msg_imported_basket: '{n}개 항목을 패널 {i}로 가져왔습니다',
        msg_basket_empty: '바스켓이 비어있습니다!',
        ph_config_name: '예: 업무용',
        ph_api_key: 'sk-...',
        ph_model: '예: gpt-4o-mini',
        ai_panel_resend: '시작 / 재시도',
        btn_layout_single: '단일 뷰',
        btn_layout_quad: '다중 뷰',
        mech_header: '// 신경망 연결 설정',
        mech_sub: '멀티 키 시스템',
        mech_hide_ep: '[ 주소 숨기기 ]',
        mech_edit_ep: '[ 주소 편집 ]',
        btn_export_json: '설정 내보내기 (JSON)',
        btn_import_json: '설정 가져오기 (JSON)',
        msg_import_success: '설정 가져오기 성공',
        msg_import_fail: '가져오기 실패: 형식이 잘못되었거나 유효하지 않은 JSON',
        prompt_sep_basket: '\n========== [ 바스켓 내용 ] ==========\n',
        prompt_item_prefix: '[항목 {n} 출처: {source}]',
        prompt_end: '\n[컨텍스트 종료]',
        prompt_fragment: '--- 대화 조각 ---',
        src_manual: '수동 입력 (새 노트)',
        src_drop: ' (드래그 앤 드롭)',
        src_file: ' (파일)',
        src_local: ' (로컬 파일)',
        tooltip_transfer_to: '{name}(으)로 컨텍스트 전송',
        tooltip_send_to: '이 응답을 {name}(으)로 전송',
        tooltip_send_all_to: '모든 응답을 {name}(으)로 전송',
        overlay_drop_add: '놓아서 바스켓에 추가',
        overlay_acquiring: '데이터 수집 중...',
        sys_btn_summary: '📝',
        sys_tooltip_summary: '로드: 요약',
        sys_prompt_summary: '다음 내용을 요약하고 핵심 사항과 결론을 나열해 주세요:',
        sys_btn_translate: '🌐',
        sys_tooltip_translate: '로드: 번역 (한국어)',
        sys_prompt_translate: '다음 내용을 자연스럽고 전문적인 한국어로 번역해 주세요:',
        sys_btn_explain: '💡',
        sys_tooltip_explain: '로드: 설명',
        sys_prompt_explain: '다음 내용을 알기 쉽게 설명해 주세요:',
        sys_btn_custom_add: '➕',
        sys_btn_custom_user: '👤',
        sys_tooltip_custom_empty: '현재 프롬프트를 템플릿으로 저장',
        sys_tooltip_custom_saved: '클릭: 불러오기\nShift+클릭: 덮어쓰기 저장',
        toast_custom_saved: '커스텀 프롬프트 저장됨 ✨',
        sys_btn_save: '💾',
        sys_tooltip_save: '커스텀 프롬프트 저장/관리 (최대 3개)',
        sys_tooltip_load: '커스텀 프롬프트 불러오기',
        prompt_save_title: '커스텀 프롬프트 저장',
        prompt_save_name_ph: '이름 입력 (예: 번역 도우미)',
        prompt_save_btn_new: '새로 저장',
        prompt_save_btn_overwrite: '선택 항목 덮어쓰기',
        prompt_save_limit: '한도(3개) 도달, 항목을 선택하여 덮어쓰세요',
        prompt_load_empty: '저장된 프롬프트 없음',
        prompt_toast_saved: '프롬프트 저장됨 ✨',
        drone_title: '텍스트를 여기로 드래그하여 저장 / 클릭하여 Context-Carry 열기',
        drone_dismiss: '확장 프로그램 아이콘을 클릭할 때까지 숨기기',
        mm_title_single: '🤖 AI 응답',
        mm_title_multi: '⚡ 워크플로우 엔진',
        mm_view_multi: '🔀 다중 노드 뷰',
        mm_view_single: '⏹ 단일 뷰',
        mm_loop_label: '루프:',
        mm_add_node: '+ 노드',
        mm_run: '▶ 실행',
        mm_stop: '⏹ 중지',
        mm_basket: '🧺 바스켓',
        mm_basket_paste: '📥 모두에게 붙여넣기',
        mm_basket_export: '⬇️ 바스켓 내보내기',
        mm_basket_import: '⬆️ 바스켓 가져오기',
        mm_send_all: '🚀 모든 플랫폼으로 전송',
        mm_basket_tip_drop: '놓아서 추가',
        mm_basket_added: '바스켓에 추가됨',
        mm_basket_empty: '바스켓이 비어있음',
        mm_basket_paste_all: '📥 모두에게 붙여넣기',
        mm_node_edit: '편집',
        mm_node_clear: '비우기',
        mm_node_copy: '복사',
        mm_node_drag: '컨텐츠 드래그',
        mm_node_run: '이 노드 실행',
        mm_save_txt: '.txt로 저장',
        mm_save_md: '.md로 저장',
        mm_confirm_del_conn: '연결을 삭제하시겠습니까?',
        mm_confirm_clear: '내용을 비우시겠습니까?',
        pip_tab_collect: '📥 수집함',
        pip_tab_flow: '⚡ 워크플로우',
        pip_drop_title: '놓아서 가져오기',
        pip_drop_sub: '(파일, 텍스트, 코드)',
        pip_tooltip_theme: '테마 전환',
        pip_tooltip_settings: '설정',
        pip_tooltip_max: '최대화/복원',
        pip_btn_paste: '붙여넣기',
        pip_btn_export: '내보내기',
        pip_btn_clear: '비우기',
        pip_empty_list: '데이터가 없습니다',
        pip_basket_title: '🧺 바스켓',
        pip_basket_empty: '비어있음',
        pip_tag_all: '전체',
        pip_node_idle: '대기',
        pip_node_running: '실행 중',
        pip_node_done: '완료',
        pip_node_error: '오류',
        pip_node_ph: '입력 대기 중...',
        pip_node_no_config: '설정 없음',
        pip_tooltip_run_node: '노드 실행',
        pip_tooltip_edit_node: '내용 편집',
        pip_tooltip_del_node: '노드 삭제',
        pip_modal_clear_title: '바스켓 비우기',
        pip_modal_clear_msg: '모든 항목을 삭제하시겠습니까? 이 작업은 되돌릴 수 없습니다.',
        pip_modal_confirm: '확인',
        pip_modal_cancel: '취소',
        pip_export_title: '바스켓 내보내기',
        pip_label_filename: '파일 이름',
        pip_label_format: '형식',
        pip_btn_save_export: '내보내기 / 저장',
        pip_toast_pasted: '클립보드에서 붙여넣음 ✨',
        pip_toast_empty: '클립보드가 비어있습니다',
        pip_toast_perm: '권한이 필요합니다 (창을 먼저 클릭하세요)',
        pip_toast_cleared: '바스켓이 비워졌습니다 🗑️',
        pip_confirm_del_item: '삭제',
        robot_comms_tab: '통신',
        drone_cargo: '화물',
        hint_drag: ' (드래그)',
        toast_input_not_found: '입력 필드를 찾을 수 없습니다. 클립보드에 복사되었습니다 📋',
        toast_file_too_large: '❌ 파일 너무 큼: {name} ({size}MB). 최대 10MB.',
        toast_file_loaded: '파일 로드됨: {name}',
        toast_manual_add_source: '수동 입력',
        btn_ping: '드래그하여 고정',
        btn_qrcode: 'QR 코드 생성',
        btn_pip: '독립 창 (PiP)',
        btn_switch_ui_robot: '기계 스타일로 전환',
        emptyMsg: '[ 화물칸 정리 완료 ]'
    }

};

if (typeof window !== 'undefined') {
    window.CC_LANG_DATA = LANG_DATA;
    window.CC_SUPPORTED_LANGS = SUPPORTED_LANGS;
}
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { LANG_DATA, SUPPORTED_LANGS };
}